### ISSUE TITLE
need more details on how to building?

### ISSUE THREAD

**Issue by andyyuan78** [jwetzl/CudaLBFGS#2]
so far, I had the 'cmake ..' and make done!

how to do the foillowing??
- build a reference implementetation on CPU with
  either float or double precision (requires Eigen),

- build test cases,

- enable error checking, verbose output and timing

- build example projects that demonstrate how the
  library is used (cf. /projects directory).

**Comment by jwetzl** [comment]
Use the CMake GUI or ccmake on the command line to enable the appropriate options.

**Comment by andyyuan78** [comment]
I turn on BUILD_PROJECTS, and use 'g' to exit.
so, next step....
